<?php

/***************************************************************
 * UW Groups Module                                            *
 *                                                             *
 * Created by the University of Washington Information School. *
 * Be sure to read README and LICENSE.                         *
 ***************************************************************/

/**
 * @file
 * uwgroups integrates UW groups web service with drupal roles.
 * Groups & group members are refreshed with every cron iteration,
 * or can be refreshed manually.
 */

module_load_include('inc', 'uwgroups', 'uwgroups');
module_load_include('inc', 'uwgroups', 'uwgroups.admin');

/**
 * Implements hook_perm().
 */
function uwgroups_perm() {
  return array(UWGWS_PERM);
}

/**
 * Implements hook_menu().
 */
function uwgroups_menu() {
  $items = array();
  
  $items['admin/settings/uwgws'] = array(
    'title' => t('UW GWS Auth'),
    'description' => t('Configure UW GWS Auth settings.'),
    'page callback' => '_uwgroups_admin_page',
    'access arguments' => array(UWGWS_PERM),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Implements hook_cron().
 */
function uwgroups_cron() {
  _uwgroups_refresh_managed();
  _uwgroups_remap_logged_in_users();
}

/**
 * Implements hook_user().
 */
function uwgroups_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'login': // update the user's groups on login
      _uwgroups_map_groups($account);
      break;
  }
}

/**
 * Implements hook_uwpubcookie_allow_user().
 */
function uwgroups_uwpubcookie_allow_user($username) {
  if (_uwgroups_var(UWGWS_ENABLE_AC)) {
    $groups = lts_command('groups ' . $username);
    
    if (!$groups || empty($groups)) {
      watchdog('UWGWS', 'Denied creation of user "%user" (could not get groups).', array('%user' => $username,), WATCHDOG_INFO);
      return FALSE;
    }
    
    if (!in_array(_uwgroups_var(UWGWS_AC_GROUP), $groups)) {
      watchdog('UWGWS', 'Denied creation of user "%user" (user not in AC group).', array('%user' => $username,), WATCHDOG_INFO);
      return FALSE;
    }
  }
  
  return TRUE;
}
