<?php

/***************************************************************
 * UW Groups Module                                            *
 *                                                             *
 * Created by the University of Washington Information School. *
 * Be sure to read README and LICENSE.                         *
 ***************************************************************/

/**
 * @file
 * uwgroups integrates UW groups web service with drupal roles.
 * Groups & group members are refreshed with every cron iteration,
 * or can be refreshed manually.
 */

module_load_include('inc', 'uwgroups', 'uwgroups');
module_load_include('inc', 'uwgroups', 'uwgroups.admin');

/**
 * Implements hook_perm().
 */
function uwgroups_permission() {
  return array(UWGWS_PERM => array(
  	'title' => 'Administer GWS',
  	'description' => 'Adjust GWS active groups'
  ));
}

/**
 * Implements hook_menu().
 */
function uwgroups_menu() {
  $items = array();
  
  $items['admin/config/people/uwgws'] = array(
    'title' => t('UW GWS Auth'),
    'description' => t('Configure UW GWS Auth settings.'),
    'page callback' => '_uwgroups_admin_page',
    'access arguments' => array(UWGWS_PERM),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Implements hook_cron().
 */
function uwgroups_cron() {
  _uwgroups_refresh_managed();
  _uwgroups_remap_logged_in_users();
}

/**
 * Implements hook_user().
 */
function uwgroups_user_login(&$edit, $account) {
  _uwgroups_map_groups($account);
}

